### ISSUE TITLE
Phase out "x-webhook-key" in webhook return payload 

### ISSUE THREAD

**Issue by jonahkaye** [metriport/metriport#1151]
### Problem

The following PR improved webhook security: https://github.com/metriport/metriport/pull/1113
It is now no longer necessary or advisable to send the customers webhook key in the webhook, since we know have an hmac in place. See: https://en.wikipedia.org/wiki/HMAC

On Dec 11th 21:00 PST the header will be moving from:

`headers: {
        "x-webhook-key": apiKey,
        "user-agent": "Metriport API",
        "x-metriport-signature": hmac
      },`
 
to 
     
`headers: {
        "user-agent": "Metriport API",
        "x-metriport-signature": hmac
      },`

### Suggested solution

We need to make customers aware of this breaking change and give them time to transition over to this new method for webhook authenticity verification.

**Comment by leite08** [comment]
Original ticket: https://github.com/metriport/metriport-internal/issues/1104

**Comment by leite08** [comment]
This was originally scheduled to be executed on Feb 15th. Today we talked about it here: https://metriport.slack.com/archives/C04DMKE9DME/p1713220232844539

**Comment by Goncharo** [comment]
New date for this is 2024-06-08
