### ISSUE TITLE
[Bug]: Document Query triggered before Patient Synchronisation with HIE

### ISSUE THREAD

**Issue by jonahkaye** [metriport/metriport#1192]
### Steps to reproduce

Trigger a document query (DQ) right after creating patient (considering the HIE synchronization hasn't finished by the time the DQ was initiated).

To force this while testing: create a patient, delete their link to the HIE from the DB, and then make a document DQ.

### What did you expect to happen?

The API deals with whether the Patient is synchronized or not without exposing this to DQ triggers.

Internally, we should upon receiving a DQ request:
- If the patient is not yet synchronized, give it some time to finish it;
- If it hasn't finished after waiting a bit, try to synchronize again;
- If it persists not synchronized, return 500 to the DQ request.

_(this will result in the DQ request/trigger taking longer to respond in some cases)_

### What is actually happening?

Get `{"download":{"status":"failed"}}` as response of DQ when the patient is not yet synchronized with HIEs.

**Comment by jonahkaye** [comment]
Updated approach:

Customers creates the Patient and gets 200 immediately - and we do  asynchronous work in the background to link the patient to HIE. 
When the customers triggers the DQ right after the Patient is created - internally we’ll deal with the status of Patient integration and might add a bit more time to wait for it to complete (or retry if it failed originally)
If, after waiting/retrying the Patient integration it still is not completed, then we’ll return a 500 with a message indicating the reason.

**Comment by leite08** [comment]
Implemented the logic below in [this PR](https://github.com/metriport/metriport/pull/1237):
- always respond 200 on patient create
- always respond 200 on document query trigger
- while executing document query
   - if patient linking is in progress, wait and try again (5 times)
   - if patient linking is not done, fail document query (sends a WH notification)
   - otherwise, trigger/execute document query
