### ISSUE TITLE
Don't send empty MR summaries

### ISSUE THREAD

**Issue by Orta21** [metriport/metriport#1515]
### Problem

If a patient has resources but those resources are not rendered in the Medical Record Summary because of filtering we will still send an empty Medical Record. 

### Suggested solution

Upon creating the Medical Record, initialize a count to gather all the resources that will be rendered. If the count is zero then we will not create a Medical Record and will return an empty webhook to the cx.

**Comment by Goncharo** [comment]
or - we can ensure that the resulting HTML has at least one row in one section
