### ISSUE TITLE
Patient search endpoint

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#1547]
### Problem

Right now, the only way to know if a patient was already registered in Metriport based on demographics is to either:

- list all patients, and do matching client-side
- create the patient again, and see if the ID returned already exists in the cx's DB

### Suggested solution

Let's add a dedicated search endpoint which will:

- take patient demographics as input
- return the patient only if we found a demographic match in our MPI

**Comment by kevinwuhoo** [comment]
I would ask that this endpoint should only return one patient and if there is more than one patient returned to return non-200 to enforce that look up is unique. This is somewhat similar to how FHIR operates.

**Comment by leite08** [comment]
Related: https://github.com/metriport/metriport/issues/1119
