### ISSUE TITLE
Add SSN support

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#1722]
### Problem

We currently only have support for DLs, but some HIT systems don't use those and prefer SSNs.

### Suggested solution

Add support for SSNs.

### Additional context

Some notes:

- CW doesn't support SSNs, so will need to take that into consideration
- Might need to modify IHE GW code to also fwd SSNs to the external GWs

**Comment by thomasyopes** [comment]
Release PR https://github.com/metriport/metriport/pull/2150
