### ISSUE TITLE
[Bug]: mimeTypes not always correctly determined from CQ

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#1745]
### Steps to reproduce

See this Slack thread for context: https://metriport.slack.com/archives/C04GEQ1GH9D/p1709706883117269?thread_ts=1709670094.144059&cid=C04GEQ1GH9D

### What did you expect to happen?

All mimeTypes are correctly set.

### What is actually happening?

There are a lot of files with `"mimeType": "application/octet-stream",` - would presume this is some sort of image due to `"description": "Insurance Card"`.

Need to correctly determine the mimeType in all situations - we're probably missing a handler [here](https://github.com/metriport/metriport/blob/f133cd98450a972a85db5bac0a11d8230a9ceabc/packages/ihe-gateway/server/CodeTemplates/Common%20Library/File%20type/File%20type.js#L1-L60), and in the [corresponding API code](https://github.com/metriport/metriport/blob/f133cd98450a972a85db5bac0a11d8230a9ceabc/packages/core/src/util/file-type.ts#L99-L149).

In fact - we should probably log a sentry if we can't determine a file type, and put the first few bytes of the file in the sentry, so we can catch these things in the future.

### Environment

```shell
prod, but probably affects all envs
```

**Comment by leite08** [comment]
Is this done after the patch on March 10th, @jonahkaye ?
