### ISSUE TITLE
[Bug]: lambdas package fails to build on clean

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#1771]
### Steps to reproduce

npm run clean
npm install
npm build

### What did you expect to happen?

everything builds fine

### What is actually happening?

lambdas fail to build

...but it works after running npm install in `/packages/lambdas`

### Environment

```shell
local
```

**Comment by leite08** [comment]
We don't use `npm install` as part of the build process:
- this can potentially update the `package-lock.json`
- it doesn't include other actions needed for lambdas

The correct command for this is `npm run install-deps`.
