### ISSUE TITLE
Map DiagnosticReport resources to Encounters

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#1978]
### Problem

Right now we map [Organization and Practitioner resources to DiagnosticReport resources](https://github.com/metriport/metriport/blob/6a9127c122a833694866c809c14cb8d43639cd02/packages/fhir-converter/src/templates/cda/Sections/History_of_Present_Illness.hbs#L9-L21) - however, there is currently no way to get the corresponding Encounter info from said resource.

### Suggested solution

Let's map the report to the corresponding encounter mentioned in the CCDA doc, putting the reference in the `DiagnosticReport.encounter` property.

**Comment by jonahkaye** [comment]
Might want to continue the trend of extracting "encounter related data" in a preprocessing step before https://github.com/metriport/metriport/blob/8c3e0d0fff0784358181dec93837dcb3953137a9/packages/fhir-converter/src/lib/inputProcessor/dateProcessor.js#L4
