### ISSUE TITLE
Don't allow future dates as date of birth (dob)

### ISSUE THREAD

**Issue by RamilGaripov** [metriport/metriport#2453]
### Problem

We've ran into an issue where we created a patient locally, but they failed to create in CW. Reason - the dob was set in the future. 

### Suggested solution

Add a validation step on patient create to make sure the dob is a valid date.

**Comment by hthkydv** [comment]
Is any one working on it i want to give it a try

**Comment by leite08** [comment]
@hthkydv thank you, but @jamestran201 already put this PR that's being merged now: https://github.com/metriport/metriport/pull/2725

Maybe another one! 😃
