### ISSUE TITLE
Apple Health Integration

### ISSUE THREAD

**Issue by rjain15** [metriport/metriport#35]
Are there plans to integrate with Apple Health to bring data from Apple Watch. I know Apple Health stores data on the device, and there are examples where you can have an app installed on the phone which can talk to Apple Health to get the data and send it over.

**Comment by Goncharo** [comment]
@rjain15

Yes indeed!

We're currently working on this, and we will ship this live in our next release, 1.1.0, which you can expect end of next week.

**Comment by rjain15** [comment]
Thanks

**Comment by Goncharo** [comment]
Hey @rjain15 - just wanted to confirm that Apple Health integrations are new available so you can get data from the Apple Watch.

Please [see our new developer docs for instructions on how to get started](https://docs.metriport.com/more-info/apple-health), and feel free to let us know if you have any questions. Of course you can reach us here, or feel free to email us at `support@metriport.com` anytime.

**Comment by Goncharo** [comment]
Closing this issue - shipped in [v1.1.0](https://github.com/metriport/metriport/releases/tag/v1.1.0).
