### ISSUE TITLE
[Feat]: Dash - Support multi-user accounts

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#350]
### Problem

Right now there is no way to create multiple users for a team account in the dashboard, so teams have to share credentials between members.

### Suggested solution

Support multi-users under one "master" account. Considerations:

- Admin/non-admin accounts?
- Admin account features: adding/removing users

**Comment by Goncharo** [comment]
auth0? supertokens?

**Comment by leite08** [comment]
Notes on https://docs.google.com/document/d/1A6TYdH2IbhGl-RGRXGOVg9DVQDNt4nbtGSQdWc55FbY/
