### ISSUE TITLE
[DAPI] Invalid UUIDs from Apple Webhook & other places

### ISSUE THREAD

**Issue by leite08** [metriport/metriport#422]
On https://github.com/metriport/metriport-internal/issues/507 we added validation for IDs to check if they are valid UUIDs.

But we've been getting issues with Apple Webhook WH calls, receiving empty IDs: https://metriport-inc.sentry.io/issues/4167229090/events/f702d01f07514cea9ed0ffd44f81dace/ (50 entries in the last 30 days as of now).

```
SequelizeDatabaseError - POST /webhook/apple/
invalid input syntax for type uuid: ""
```

**Comment by Goncharo** [comment]
Haven't seen this issue for almost a month now - probably was just some bug in our Apple Health lib and/or Kodda implementation.
