### ISSUE TITLE
[Feat]: DAPI - List connected users

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#459]
### Problem

Right now there's no way to gain visibility into the connected users that were previously provisioned.

### Suggested solution

Create an endpoint that will list all connected users, along with the connected providers. Perhaps returning an JSON response with the following format:

```
{
    connectedUsers: [
        {
            metriportUserId: "06C68E2A-0562-11EE-B2A6-A2F55214B7C1",
            appUserId: "1234",
            connectedProviders: ["fitbit", "oura"]
        },
        {
            metriportUserId: "06C690E6-0562-11EE-B2A6-A2F55214B7C1",
            appUserId: "6666",
            connectedProviders: ["whoop", "garmin"]
        }
    ]
}
```

### Additional context

SDK + docs will need to be updated.

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.

**Comment by Goncharo** [comment]
@tarunsamanta2k20 - sounds great, feel free to create a PR and we'll review it once it's up.

**Comment by Goncharo** [comment]
Hey @tarunsamanta2k20 - any progress on your end? We were hoping to tackle this soon.
