### ISSUE TITLE
Update prep-deploy script

### ISSUE THREAD

**Issue by Orta21** [metriport/metriport#499]
### Problem

When deploying we are only prepping the `garmin` and `token-auth` lambdas. 

### Suggested solution

Create individual scripts for each additional lambda and add those to the `prep-deploy` script

**Comment by leite08** [comment]
Being done on https://github.com/metriport/metriport/pull/574/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
