### ISSUE TITLE
[Bug]: Update doc query progress on documentation

### ISSUE THREAD

**Issue by leite08** [metriport/metriport#539]
### Steps to reproduce

- docs
   - “start document query” refers to and updates the status of document query to... I suggest it refers to …the status of document download...
      - and explain something like “the doc query triggers two actions, download and conversion… each have their own status…”
   - the example on “List documents” still refers to queryStatus
      - it also uses required to response props, I’d suggest we mark the ones that are optional optional instead
- sdk
   - add @deprecated to the respective documentQuerySchema

### What did you expect to happen?

documentation and sdk to be fully matching the new doc query progress logic

### What is actually happening?

docs and sdk are not completely updated to the new doc query progress logic

**Comment by Goncharo** [comment]
This is no longer an issue, was updated under one of the many doc query PRs
