### ISSUE TITLE
Create tests for new methods in the DAPI SDK

### ISSUE THREAD

**Issue by RamilGaripov** [metriport/metriport#540]
refs. https://github.com/metriport/metriport/issues/426

### Problem

DAPI Metriport Client got a couple new methods - they need to be properly tested

- deleteUser() -> NEW METHOD
- revokeUserAccessToProvider() -> RECEIVED CHANGES

### Suggested solution

Create E2E tests for both methods

**Comment by leite08** [comment]
DAPI has been sunset
