### ISSUE TITLE
[Bug]: CDA to Vis Lambda returns error in url

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#598]
### Steps to reproduce

Get the download URL for a file in PDF format, and rig the CDA to Vis lambda to throw an error.

### What did you expect to happen?

Error is handled gracefully in a standardized response.

### What is actually happening?

The error gets returned to the caller in the `url` property with a `200` response.

### Environment

```shell
prod
```

**Comment by leite08** [comment]
Moving this back to the queue after this issue: https://metriport.slack.com/archives/C04DMKE9DME/p1697642982020239

> the issue which may be for all lambdas that we invoke is that even if it errors it will return a 200 and then the body will be the error...
> what we could do is if there is an error return an “error payload” or nothing at all so we can handle it better
> could also try to force a return status on the lambda upon error so the client identifies it more easily

**Comment by leite08** [comment]
Fixed by https://github.com/metriport/metriport-internal/issues/1182

**Comment by leite08** [comment]
Sorry, this is still being shipped. Will update the status when done.
