### ISSUE TITLE
Google Fit - inclusion of timezones into the daily summaries

### ISSUE THREAD

**Issue by RamilGaripov** [metriport/metriport#733]
### Problem

Currently, the daily activity summary for Google Fit returns a 24-hour window starting on 12:00am UTC, which doesn't take into account the user's timezone, resulting in data misplacement. I.e. if you want to return a daily summary to the user for July 1st, who lives by PST, you will actually end up sending their data from June 30 at 5pm until July 1 at 5 pm. 

The activity payload for Google Fit currently includes a summary of activities for the day, as well as a breakdown for each activity's contribution to things like step_count, calories burned, etc. 

We could tell our CXs to query surrounding days as well and group them by activity start/end time. The problem with that is that user data such as step count and distance can be added by 3-rd party connected providers, such as Apple Health, and resides as datapoints that we query for, but are NOT associated with any activity (unless a smart watch is used - according to docs but untested). As a result, the returned payload's logged activities will not add up to the numbers in the summary AND the summary will only match the UTC, and contain ambiguous information for other timezones. 

### Suggested solution

Group the data into hourly buckets and add that as a separate attribute in the payload, like this: 

![Image](https://github.com/metriport/metriport/assets/90670087/b4c24992-4357-4a15-b797-fa0e7f3c0306)

This will allow our CX to organize the data in a more structured manner and return payloads to their users based on their timezones

### Alternatives

- Put this `hourly_breakdown` attribute inside `summary`
- Include another optional parameter to the `GET /activity` endpoint to allow passing of the user's timezone. This way, if we know what timezone the user lives in, we could incorporate that into our requests to providers and fetch more accurate data. i.e. with Google Fit, we could query for `2023-08-03T07:00:00` to receive correct activity and summary breakdowns for a PST user. This seems like a much larger way to go about things, but perhaps it would let us take care of multiple providers having similar issues. 
- Inform our CX of this limitation for users who don't use smart watches? MVP with logged activities works. More fixes could come later?

**Comment by RamilGaripov** [comment]
I've been looking into this, but I haven't been able to hit [this endpoint](https://developers.google.com/fit/rest/v1/datasets) - the error is ACCESS_TOKEN_SCOPE_INSUFFICIENT even though I added ALL possible scopes into my burner app.

**Comment by Goncharo** [comment]
see this Slack thread for context https://metriport.slack.com/archives/C04DMKE9DME/p1691086557647459
