### ISSUE TITLE
[Bug]: Apple health dissapears in connect widget with react-native SDK

### ISSUE THREAD

**Issue by jhenriquezs** [metriport/metriport#776]
### Steps to reproduce

- Use react-native SDK and iOS device.
- Create a component with the `MetriportWidget`, and don't pass providers as props. 
```html
<MetriportWidget
    token="CONNECT_TOKEN"
    clientApiKey="CLIENT_API_KEY"
    sandbox={false}
    style={styles.box}
/>
```
- When running the app, connect any provider that is not apple health.

### What did you expect to happen?

Return to the initial page with all the providers supported by metriport.

### What is actually happening?

The apple health option disappears after returning to the initial page.

### Environment

```shell
- MacOS ventura 13.5
- Expo SDK 48
- Simulator(iOS 16.4)
- @metriport/react-native-sdk: 1.0.7
- react-native: 0.71.8
- Node: v18.16.1
```

### Any additional comments?

A solution to bypass the problem is specifying the providers in the component (e.g):

```html
<MetriportWidget
    token="CONNECT_TOKEN"
    clientApiKey="CLIENT_API_KEY"
    sandbox={false}
    style={styles.box}
    providers={['apple', 'google', 'garmin']}
/>
```

**Comment by Goncharo** [comment]
Shipped to prod 🚀
