### ISSUE TITLE
[Bug]:  400 error of getting Organization using the Consolidated endpoint

### ISSUE THREAD

**Issue by Fotonix** [metriport/metriport#844]
### Steps to reproduce

Here is a screenshot of Postman:
![MicrosoftTeams-image (4)](https://github.com/metriport/metriport/assets/12040462/08f62bb1-6d38-4827-827d-0060fafb9199)

### What did you expect to happen?

Get an organization entity

### What is actually happening?

400 HTTP error

### Environment

```shell
Sandbox
```

**Comment by Goncharo** [comment]
as discussed offline, the solution for this was to reference the organization in `contains` in the FHIR resource
