### ISSUE TITLE
Revamp GET /document

### ISSUE THREAD

**Issue by leite08** [metriport/metriport#888]
Currently, the endpoint to retrieve document references returns mostly metadata/file info (filename, location, mime type, size).

Let's revamp it so it also returns domain specific data, like:
- Organization
- Practitioner
- Context

Ideally we would make this endpoint return the actual FHIR resource, so no need to convert to a different representation of the data - which would likely be limited anyways.

Also, we need to be able to filter doc refs by:
- date range
- org name
- practitioner name

Todo:
- [x] Update API
- [x] Update SDK
- [x] Update Docs
- [ ] Update Dash

**Comment by Goncharo** [comment]
Note that for now we can add a filter by date range, and then a string match filter for everything else
